type: object
required:
  - requireDateOfBirth
properties:
  requireDateOfBirth:
    description: Setting to require date of birth.
    type: boolean
  _links:
    type: array
    description: The links related to resource.
    readOnly: true
    minItems: 1
    items:
      anyOf:
        - $ref: ./Links/SelfLink.yaml
