type: object
required:
  - requireDateOfBirth
properties:
  id:
    description: The credential identifier string.
    readOnly: true
    allOf:
      - $ref: ./ResourceId.yaml
  requireDateOfBirth:
    description: Setting to require date of birth
    type: boolean
  _links:
    type: array
    description: The links related to resource.
    readOnly: true
    minItems: 1
    items:
      anyOf:
        - $ref: ./Links/SelfLink.yaml
